// <auto-generated />
using Assignment_ASP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_ASP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230819174713_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment_ASP.Model.FriendsModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("friends");

                    b.HasData(
                        new
                        {
                            Name = "Name1",
                            ProfileImage = "Photo1.jpg"
                        },
                        new
                        {
                            Name = "Name2",
                            ProfileImage = "Photo2.jpg"
                        },
                        new
                        {
                            Name = "Name3",
                            ProfileImage = "Photo3.jpg"
                        },
                        new
                        {
                            Name = "Name4",
                            ProfileImage = "Photo4.jpg"
                        },
                        new
                        {
                            Name = "Name5",
                            ProfileImage = "Photo5.jpg"
                        },
                        new
                        {
                            Name = "Name6",
                            ProfileImage = "Photo6.jpg"
                        },
                        new
                        {
                            Name = "Name7",
                            ProfileImage = "Photo7.jpg"
                        },
                        new
                        {
                            Name = "Name8",
                            ProfileImage = "Photo8.jpg"
                        },
                        new
                        {
                            Name = "Name9",
                            ProfileImage = "Photo9.jpg"
                        },
                        new
                        {
                            Name = "Name10",
                            ProfileImage = "Photo10.jpg"
                        },
                        new
                        {
                            Name = "Name11",
                            ProfileImage = "Photo11.jpg"
                        },
                        new
                        {
                            Name = "Name12",
                            ProfileImage = "Photo12.jpg"
                        },
                        new
                        {
                            Name = "Name13",
                            ProfileImage = "Photo13.jpg"
                        },
                        new
                        {
                            Name = "Name14",
                            ProfileImage = "Photo14.jpg"
                        },
                        new
                        {
                            Name = "Name15",
                            ProfileImage = "Photo15.jpg"
                        },
                        new
                        {
                            Name = "Name16",
                            ProfileImage = "Photo16.jpg"
                        },
                        new
                        {
                            Name = "Name17",
                            ProfileImage = "Photo17.jpg"
                        },
                        new
                        {
                            Name = "Name18",
                            ProfileImage = "Photo18.jpg"
                        },
                        new
                        {
                            Name = "Name19",
                            ProfileImage = "Photo19.jpg"
                        },
                        new
                        {
                            Name = "Name20",
                            ProfileImage = "Photo20.jpg"
                        },
                        new
                        {
                            Name = "Name21",
                            ProfileImage = "Photo21.jpg"
                        },
                        new
                        {
                            Name = "Name22",
                            ProfileImage = "Photo22.jpg"
                        },
                        new
                        {
                            Name = "Name23",
                            ProfileImage = "Photo23.jpg"
                        },
                        new
                        {
                            Name = "Name24",
                            ProfileImage = "Photo24.jpg"
                        },
                        new
                        {
                            Name = "Name25",
                            ProfileImage = "Photo25.jpg"
                        },
                        new
                        {
                            Name = "Name26",
                            ProfileImage = "Photo26.jpg"
                        },
                        new
                        {
                            Name = "Name27",
                            ProfileImage = "Photo27.jpg"
                        },
                        new
                        {
                            Name = "Name28",
                            ProfileImage = "Photo28.jpg"
                        },
                        new
                        {
                            Name = "Name29",
                            ProfileImage = "Photo29.jpg"
                        },
                        new
                        {
                            Name = "Name30",
                            ProfileImage = "Photo30.jpg"
                        },
                        new
                        {
                            Name = "Name31",
                            ProfileImage = "Photo31.jpg"
                        },
                        new
                        {
                            Name = "Name32",
                            ProfileImage = "Photo32.jpg"
                        },
                        new
                        {
                            Name = "Name33",
                            ProfileImage = "Photo33.jpg"
                        },
                        new
                        {
                            Name = "Name34",
                            ProfileImage = "Photo34.jpg"
                        },
                        new
                        {
                            Name = "Name35",
                            ProfileImage = "Photo35.jpg"
                        },
                        new
                        {
                            Name = "Name36",
                            ProfileImage = "Photo36.jpg"
                        },
                        new
                        {
                            Name = "Name37",
                            ProfileImage = "Photo37.jpg"
                        },
                        new
                        {
                            Name = "Name38",
                            ProfileImage = "Photo38.jpg"
                        },
                        new
                        {
                            Name = "Name39",
                            ProfileImage = "Photo39.jpg"
                        },
                        new
                        {
                            Name = "Name40",
                            ProfileImage = "Photo40.jpg"
                        },
                        new
                        {
                            Name = "Name41",
                            ProfileImage = "Photo41.jpg"
                        },
                        new
                        {
                            Name = "Name42",
                            ProfileImage = "Photo42.jpg"
                        },
                        new
                        {
                            Name = "Name43",
                            ProfileImage = "Photo43.jpg"
                        },
                        new
                        {
                            Name = "Name44",
                            ProfileImage = "Photo44.jpg"
                        },
                        new
                        {
                            Name = "Name45",
                            ProfileImage = "Photo45.jpg"
                        },
                        new
                        {
                            Name = "Name46",
                            ProfileImage = "Photo46.jpg"
                        },
                        new
                        {
                            Name = "Name47",
                            ProfileImage = "Photo47.jpg"
                        },
                        new
                        {
                            Name = "Name48",
                            ProfileImage = "Photo48.jpg"
                        },
                        new
                        {
                            Name = "Name49",
                            ProfileImage = "Photo49.jpg"
                        },
                        new
                        {
                            Name = "Name50",
                            ProfileImage = "Photo50.jpg"
                        },
                        new
                        {
                            Name = "Name51",
                            ProfileImage = "Photo51.jpg"
                        },
                        new
                        {
                            Name = "Name52",
                            ProfileImage = "Photo52.jpg"
                        },
                        new
                        {
                            Name = "Name53",
                            ProfileImage = "Photo53.jpg"
                        },
                        new
                        {
                            Name = "Name54",
                            ProfileImage = "Photo54.jpg"
                        },
                        new
                        {
                            Name = "Name55",
                            ProfileImage = "Photo55.jpg"
                        },
                        new
                        {
                            Name = "Name56",
                            ProfileImage = "Photo56.jpg"
                        },
                        new
                        {
                            Name = "Name57",
                            ProfileImage = "Photo57.jpg"
                        },
                        new
                        {
                            Name = "Name58",
                            ProfileImage = "Photo58.jpg"
                        },
                        new
                        {
                            Name = "Name59",
                            ProfileImage = "Photo59.jpg"
                        },
                        new
                        {
                            Name = "Name60",
                            ProfileImage = "Photo60.jpg"
                        },
                        new
                        {
                            Name = "Name61",
                            ProfileImage = "Photo61.jpg"
                        },
                        new
                        {
                            Name = "Name62",
                            ProfileImage = "Photo62.jpg"
                        },
                        new
                        {
                            Name = "Name63",
                            ProfileImage = "Photo63.jpg"
                        },
                        new
                        {
                            Name = "Name64",
                            ProfileImage = "Photo64.jpg"
                        },
                        new
                        {
                            Name = "Name65",
                            ProfileImage = "Photo65.jpg"
                        },
                        new
                        {
                            Name = "Name66",
                            ProfileImage = "Photo66.jpg"
                        },
                        new
                        {
                            Name = "Name67",
                            ProfileImage = "Photo67.jpg"
                        },
                        new
                        {
                            Name = "Name68",
                            ProfileImage = "Photo68.jpg"
                        },
                        new
                        {
                            Name = "Name69",
                            ProfileImage = "Photo69.jpg"
                        },
                        new
                        {
                            Name = "Name70",
                            ProfileImage = "Photo70.jpg"
                        },
                        new
                        {
                            Name = "Name71",
                            ProfileImage = "Photo71.jpg"
                        },
                        new
                        {
                            Name = "Name72",
                            ProfileImage = "Photo72.jpg"
                        },
                        new
                        {
                            Name = "Name73",
                            ProfileImage = "Photo73.jpg"
                        },
                        new
                        {
                            Name = "Name74",
                            ProfileImage = "Photo74.jpg"
                        },
                        new
                        {
                            Name = "Name75",
                            ProfileImage = "Photo75.jpg"
                        },
                        new
                        {
                            Name = "Name76",
                            ProfileImage = "Photo76.jpg"
                        },
                        new
                        {
                            Name = "Name77",
                            ProfileImage = "Photo77.jpg"
                        },
                        new
                        {
                            Name = "Name78",
                            ProfileImage = "Photo78.jpg"
                        },
                        new
                        {
                            Name = "Name79",
                            ProfileImage = "Photo79.jpg"
                        },
                        new
                        {
                            Name = "Name80",
                            ProfileImage = "Photo80.jpg"
                        },
                        new
                        {
                            Name = "Name81",
                            ProfileImage = "Photo81.jpg"
                        },
                        new
                        {
                            Name = "Name82",
                            ProfileImage = "Photo82.jpg"
                        },
                        new
                        {
                            Name = "Name83",
                            ProfileImage = "Photo83.jpg"
                        },
                        new
                        {
                            Name = "Name84",
                            ProfileImage = "Photo84.jpg"
                        },
                        new
                        {
                            Name = "Name85",
                            ProfileImage = "Photo85.jpg"
                        },
                        new
                        {
                            Name = "Name86",
                            ProfileImage = "Photo86.jpg"
                        },
                        new
                        {
                            Name = "Name87",
                            ProfileImage = "Photo87.jpg"
                        },
                        new
                        {
                            Name = "Name88",
                            ProfileImage = "Photo88.jpg"
                        },
                        new
                        {
                            Name = "Name89",
                            ProfileImage = "Photo89.jpg"
                        },
                        new
                        {
                            Name = "Name90",
                            ProfileImage = "Photo90.jpg"
                        },
                        new
                        {
                            Name = "Name91",
                            ProfileImage = "Photo91.jpg"
                        },
                        new
                        {
                            Name = "Name92",
                            ProfileImage = "Photo92.jpg"
                        },
                        new
                        {
                            Name = "Name93",
                            ProfileImage = "Photo93.jpg"
                        },
                        new
                        {
                            Name = "Name94",
                            ProfileImage = "Photo94.jpg"
                        },
                        new
                        {
                            Name = "Name95",
                            ProfileImage = "Photo95.jpg"
                        },
                        new
                        {
                            Name = "Name96",
                            ProfileImage = "Photo96.jpg"
                        },
                        new
                        {
                            Name = "Name97",
                            ProfileImage = "Photo97.jpg"
                        },
                        new
                        {
                            Name = "Name98",
                            ProfileImage = "Photo98.jpg"
                        },
                        new
                        {
                            Name = "Name99",
                            ProfileImage = "Photo99.jpg"
                        },
                        new
                        {
                            Name = "Name100",
                            ProfileImage = "Photo100.jpg"
                        });
                });

            modelBuilder.Entity("Assignment_ASP.Model.PostDataModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("postData");

                    b.HasData(
                        new
                        {
                            Name = "Test",
                            PostImage = "Test-img.jpg",
                            ProfileImage = "Profile-test-img.jpg",
                            Time = "18th Aug"
                        });
                });

            modelBuilder.Entity("Assignment_ASP.Model.UserFriends", b =>
                {
                    b.Property<int>("UserModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserModelId", "Name");

                    b.HasIndex("Name");

                    b.ToTable("UserFriends");
                });

            modelBuilder.Entity("Assignment_ASP.Model.UserModel", b =>
                {
                    b.Property<int>("UserModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserModelId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserModelId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserModelId = 1,
                            Name = "Name1",
                            ProfileImage = "Photo1.jpg"
                        },
                        new
                        {
                            UserModelId = 2,
                            Name = "Name2",
                            ProfileImage = "Photo2.jpg"
                        },
                        new
                        {
                            UserModelId = 3,
                            Name = "Name3",
                            ProfileImage = "Photo3.jpg"
                        },
                        new
                        {
                            UserModelId = 4,
                            Name = "Name4",
                            ProfileImage = "Photo4.jpg"
                        },
                        new
                        {
                            UserModelId = 5,
                            Name = "Name5",
                            ProfileImage = "Photo5.jpg"
                        },
                        new
                        {
                            UserModelId = 6,
                            Name = "Name6",
                            ProfileImage = "Photo6.jpg"
                        },
                        new
                        {
                            UserModelId = 7,
                            Name = "Name7",
                            ProfileImage = "Photo7.jpg"
                        },
                        new
                        {
                            UserModelId = 8,
                            Name = "Name8",
                            ProfileImage = "Photo8.jpg"
                        },
                        new
                        {
                            UserModelId = 9,
                            Name = "Name9",
                            ProfileImage = "Photo9.jpg"
                        },
                        new
                        {
                            UserModelId = 10,
                            Name = "Name10",
                            ProfileImage = "Photo10.jpg"
                        },
                        new
                        {
                            UserModelId = 11,
                            Name = "Name11",
                            ProfileImage = "Photo11.jpg"
                        },
                        new
                        {
                            UserModelId = 12,
                            Name = "Name12",
                            ProfileImage = "Photo12.jpg"
                        },
                        new
                        {
                            UserModelId = 13,
                            Name = "Name13",
                            ProfileImage = "Photo13.jpg"
                        },
                        new
                        {
                            UserModelId = 14,
                            Name = "Name14",
                            ProfileImage = "Photo14.jpg"
                        },
                        new
                        {
                            UserModelId = 15,
                            Name = "Name15",
                            ProfileImage = "Photo15.jpg"
                        },
                        new
                        {
                            UserModelId = 16,
                            Name = "Name16",
                            ProfileImage = "Photo16.jpg"
                        },
                        new
                        {
                            UserModelId = 17,
                            Name = "Name17",
                            ProfileImage = "Photo17.jpg"
                        },
                        new
                        {
                            UserModelId = 18,
                            Name = "Name18",
                            ProfileImage = "Photo18.jpg"
                        },
                        new
                        {
                            UserModelId = 19,
                            Name = "Name19",
                            ProfileImage = "Photo19.jpg"
                        },
                        new
                        {
                            UserModelId = 20,
                            Name = "Name20",
                            ProfileImage = "Photo20.jpg"
                        },
                        new
                        {
                            UserModelId = 21,
                            Name = "Name21",
                            ProfileImage = "Photo21.jpg"
                        },
                        new
                        {
                            UserModelId = 22,
                            Name = "Name22",
                            ProfileImage = "Photo22.jpg"
                        },
                        new
                        {
                            UserModelId = 23,
                            Name = "Name23",
                            ProfileImage = "Photo23.jpg"
                        },
                        new
                        {
                            UserModelId = 24,
                            Name = "Name24",
                            ProfileImage = "Photo24.jpg"
                        },
                        new
                        {
                            UserModelId = 25,
                            Name = "Name25",
                            ProfileImage = "Photo25.jpg"
                        },
                        new
                        {
                            UserModelId = 26,
                            Name = "Name26",
                            ProfileImage = "Photo26.jpg"
                        },
                        new
                        {
                            UserModelId = 27,
                            Name = "Name27",
                            ProfileImage = "Photo27.jpg"
                        },
                        new
                        {
                            UserModelId = 28,
                            Name = "Name28",
                            ProfileImage = "Photo28.jpg"
                        },
                        new
                        {
                            UserModelId = 29,
                            Name = "Name29",
                            ProfileImage = "Photo29.jpg"
                        },
                        new
                        {
                            UserModelId = 30,
                            Name = "Name30",
                            ProfileImage = "Photo30.jpg"
                        },
                        new
                        {
                            UserModelId = 31,
                            Name = "Name31",
                            ProfileImage = "Photo31.jpg"
                        },
                        new
                        {
                            UserModelId = 32,
                            Name = "Name32",
                            ProfileImage = "Photo32.jpg"
                        },
                        new
                        {
                            UserModelId = 33,
                            Name = "Name33",
                            ProfileImage = "Photo33.jpg"
                        },
                        new
                        {
                            UserModelId = 34,
                            Name = "Name34",
                            ProfileImage = "Photo34.jpg"
                        },
                        new
                        {
                            UserModelId = 35,
                            Name = "Name35",
                            ProfileImage = "Photo35.jpg"
                        },
                        new
                        {
                            UserModelId = 36,
                            Name = "Name36",
                            ProfileImage = "Photo36.jpg"
                        },
                        new
                        {
                            UserModelId = 37,
                            Name = "Name37",
                            ProfileImage = "Photo37.jpg"
                        },
                        new
                        {
                            UserModelId = 38,
                            Name = "Name38",
                            ProfileImage = "Photo38.jpg"
                        },
                        new
                        {
                            UserModelId = 39,
                            Name = "Name39",
                            ProfileImage = "Photo39.jpg"
                        },
                        new
                        {
                            UserModelId = 40,
                            Name = "Name40",
                            ProfileImage = "Photo40.jpg"
                        },
                        new
                        {
                            UserModelId = 41,
                            Name = "Name41",
                            ProfileImage = "Photo41.jpg"
                        },
                        new
                        {
                            UserModelId = 42,
                            Name = "Name42",
                            ProfileImage = "Photo42.jpg"
                        },
                        new
                        {
                            UserModelId = 43,
                            Name = "Name43",
                            ProfileImage = "Photo43.jpg"
                        },
                        new
                        {
                            UserModelId = 44,
                            Name = "Name44",
                            ProfileImage = "Photo44.jpg"
                        },
                        new
                        {
                            UserModelId = 45,
                            Name = "Name45",
                            ProfileImage = "Photo45.jpg"
                        },
                        new
                        {
                            UserModelId = 46,
                            Name = "Name46",
                            ProfileImage = "Photo46.jpg"
                        },
                        new
                        {
                            UserModelId = 47,
                            Name = "Name47",
                            ProfileImage = "Photo47.jpg"
                        },
                        new
                        {
                            UserModelId = 48,
                            Name = "Name48",
                            ProfileImage = "Photo48.jpg"
                        },
                        new
                        {
                            UserModelId = 49,
                            Name = "Name49",
                            ProfileImage = "Photo49.jpg"
                        },
                        new
                        {
                            UserModelId = 50,
                            Name = "Name50",
                            ProfileImage = "Photo50.jpg"
                        },
                        new
                        {
                            UserModelId = 51,
                            Name = "Name51",
                            ProfileImage = "Photo51.jpg"
                        },
                        new
                        {
                            UserModelId = 52,
                            Name = "Name52",
                            ProfileImage = "Photo52.jpg"
                        },
                        new
                        {
                            UserModelId = 53,
                            Name = "Name53",
                            ProfileImage = "Photo53.jpg"
                        },
                        new
                        {
                            UserModelId = 54,
                            Name = "Name54",
                            ProfileImage = "Photo54.jpg"
                        },
                        new
                        {
                            UserModelId = 55,
                            Name = "Name55",
                            ProfileImage = "Photo55.jpg"
                        },
                        new
                        {
                            UserModelId = 56,
                            Name = "Name56",
                            ProfileImage = "Photo56.jpg"
                        },
                        new
                        {
                            UserModelId = 57,
                            Name = "Name57",
                            ProfileImage = "Photo57.jpg"
                        },
                        new
                        {
                            UserModelId = 58,
                            Name = "Name58",
                            ProfileImage = "Photo58.jpg"
                        },
                        new
                        {
                            UserModelId = 59,
                            Name = "Name59",
                            ProfileImage = "Photo59.jpg"
                        },
                        new
                        {
                            UserModelId = 60,
                            Name = "Name60",
                            ProfileImage = "Photo60.jpg"
                        },
                        new
                        {
                            UserModelId = 61,
                            Name = "Name61",
                            ProfileImage = "Photo61.jpg"
                        },
                        new
                        {
                            UserModelId = 62,
                            Name = "Name62",
                            ProfileImage = "Photo62.jpg"
                        },
                        new
                        {
                            UserModelId = 63,
                            Name = "Name63",
                            ProfileImage = "Photo63.jpg"
                        },
                        new
                        {
                            UserModelId = 64,
                            Name = "Name64",
                            ProfileImage = "Photo64.jpg"
                        },
                        new
                        {
                            UserModelId = 65,
                            Name = "Name65",
                            ProfileImage = "Photo65.jpg"
                        },
                        new
                        {
                            UserModelId = 66,
                            Name = "Name66",
                            ProfileImage = "Photo66.jpg"
                        },
                        new
                        {
                            UserModelId = 67,
                            Name = "Name67",
                            ProfileImage = "Photo67.jpg"
                        },
                        new
                        {
                            UserModelId = 68,
                            Name = "Name68",
                            ProfileImage = "Photo68.jpg"
                        },
                        new
                        {
                            UserModelId = 69,
                            Name = "Name69",
                            ProfileImage = "Photo69.jpg"
                        },
                        new
                        {
                            UserModelId = 70,
                            Name = "Name70",
                            ProfileImage = "Photo70.jpg"
                        },
                        new
                        {
                            UserModelId = 71,
                            Name = "Name71",
                            ProfileImage = "Photo71.jpg"
                        },
                        new
                        {
                            UserModelId = 72,
                            Name = "Name72",
                            ProfileImage = "Photo72.jpg"
                        },
                        new
                        {
                            UserModelId = 73,
                            Name = "Name73",
                            ProfileImage = "Photo73.jpg"
                        },
                        new
                        {
                            UserModelId = 74,
                            Name = "Name74",
                            ProfileImage = "Photo74.jpg"
                        },
                        new
                        {
                            UserModelId = 75,
                            Name = "Name75",
                            ProfileImage = "Photo75.jpg"
                        },
                        new
                        {
                            UserModelId = 76,
                            Name = "Name76",
                            ProfileImage = "Photo76.jpg"
                        },
                        new
                        {
                            UserModelId = 77,
                            Name = "Name77",
                            ProfileImage = "Photo77.jpg"
                        },
                        new
                        {
                            UserModelId = 78,
                            Name = "Name78",
                            ProfileImage = "Photo78.jpg"
                        },
                        new
                        {
                            UserModelId = 79,
                            Name = "Name79",
                            ProfileImage = "Photo79.jpg"
                        },
                        new
                        {
                            UserModelId = 80,
                            Name = "Name80",
                            ProfileImage = "Photo80.jpg"
                        },
                        new
                        {
                            UserModelId = 81,
                            Name = "Name81",
                            ProfileImage = "Photo81.jpg"
                        },
                        new
                        {
                            UserModelId = 82,
                            Name = "Name82",
                            ProfileImage = "Photo82.jpg"
                        },
                        new
                        {
                            UserModelId = 83,
                            Name = "Name83",
                            ProfileImage = "Photo83.jpg"
                        },
                        new
                        {
                            UserModelId = 84,
                            Name = "Name84",
                            ProfileImage = "Photo84.jpg"
                        },
                        new
                        {
                            UserModelId = 85,
                            Name = "Name85",
                            ProfileImage = "Photo85.jpg"
                        },
                        new
                        {
                            UserModelId = 86,
                            Name = "Name86",
                            ProfileImage = "Photo86.jpg"
                        },
                        new
                        {
                            UserModelId = 87,
                            Name = "Name87",
                            ProfileImage = "Photo87.jpg"
                        },
                        new
                        {
                            UserModelId = 88,
                            Name = "Name88",
                            ProfileImage = "Photo88.jpg"
                        },
                        new
                        {
                            UserModelId = 89,
                            Name = "Name89",
                            ProfileImage = "Photo89.jpg"
                        },
                        new
                        {
                            UserModelId = 90,
                            Name = "Name90",
                            ProfileImage = "Photo90.jpg"
                        },
                        new
                        {
                            UserModelId = 91,
                            Name = "Name91",
                            ProfileImage = "Photo91.jpg"
                        },
                        new
                        {
                            UserModelId = 92,
                            Name = "Name92",
                            ProfileImage = "Photo92.jpg"
                        },
                        new
                        {
                            UserModelId = 93,
                            Name = "Name93",
                            ProfileImage = "Photo93.jpg"
                        },
                        new
                        {
                            UserModelId = 94,
                            Name = "Name94",
                            ProfileImage = "Photo94.jpg"
                        },
                        new
                        {
                            UserModelId = 95,
                            Name = "Name95",
                            ProfileImage = "Photo95.jpg"
                        },
                        new
                        {
                            UserModelId = 96,
                            Name = "Name96",
                            ProfileImage = "Photo96.jpg"
                        },
                        new
                        {
                            UserModelId = 97,
                            Name = "Name97",
                            ProfileImage = "Photo97.jpg"
                        },
                        new
                        {
                            UserModelId = 98,
                            Name = "Name98",
                            ProfileImage = "Photo98.jpg"
                        },
                        new
                        {
                            UserModelId = 99,
                            Name = "Name99",
                            ProfileImage = "Photo99.jpg"
                        },
                        new
                        {
                            UserModelId = 100,
                            Name = "Name100",
                            ProfileImage = "Photo100.jpg"
                        });
                });

            modelBuilder.Entity("Assignment_ASP.Model.UserFriends", b =>
                {
                    b.HasOne("Assignment_ASP.Model.FriendsModel", "friends")
                        .WithMany("users")
                        .HasForeignKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_ASP.Model.UserModel", "Users")
                        .WithMany("friends")
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");

                    b.Navigation("friends");
                });

            modelBuilder.Entity("Assignment_ASP.Model.FriendsModel", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("Assignment_ASP.Model.UserModel", b =>
                {
                    b.Navigation("friends");
                });
#pragma warning restore 612, 618
        }
    }
}
